//! Checks that README.md and doc/wiki/*.md, generated by `satex-doc` from
//! the templates in doc/src, are up to date with what's checked in.

use std::process::Command;

#[test]
fn generated_docs_are_up_to_date() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let output = Command::new(env!("CARGO_BIN_EXE_satex-doc"))
        .arg("--check")
        // `satex-doc` runs real commands, against the binary of this profile.
        .env("SATEX_DOC_BIN", env!("CARGO_BIN_EXE_satex"))
        .current_dir(manifest_dir)
        .output()
        .expect("failed to run satex-doc");

    assert!(
        output.status.success(),
        "README.md and doc/wiki/*.md are stale; regenerate with \
         `cargo run --release --features doc --bin satex-doc`\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}
