//! Checks that README.md and doc/wiki/*.md, generated by `satex-doc` from
//! the templates in doc/src, are up to date with what's checked in.
//! Skipped when `./target/release/satex` has not been built, since the
//! generator runs real commands against it.

use std::path::Path;
use std::process::Command;

#[test]
fn generated_docs_are_up_to_date() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let satex_bin = Path::new(manifest_dir).join("target/release/satex");
    if !satex_bin.exists() {
        eprintln!(
            "skipping: {} not built; run `cargo build --release` first",
            satex_bin.display()
        );
        return;
    }

    let output = Command::new(env!("CARGO_BIN_EXE_satex-doc"))
        .arg("--check")
        .current_dir(manifest_dir)
        .output()
        .expect("failed to run satex-doc");

    assert!(
        output.status.success(),
        "README.md and doc/wiki/*.md are stale; regenerate with \
         `cargo run --release --features doc --bin satex-doc`\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}
